# Generated by Django 5.2.7 on 2025-10-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scanjob_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='options',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
