# Generated by Django 5.2.7 on 2025-10-14 23:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_scanjob_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanjob',
            name='id',
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='job_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
